### ISSUE TITLE
(refactor) Separate repository default/core data from institution data

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#1]
There are some pieces of data used to power the bhima application that are independent of any installation.  This includes `language`s, `unit`s, and `report`s, to name a few.  These tables should be separated out of the test data so that an institution can be cleanly updated - at the moment, both core and institution specific data is intermingled.

**Comment by sfount** [comment]
This should be addressed with https://github.com/IMA-WorldHealth/bhima-2.X/pull/934. I'm not sure when the best time for that to be merged is.

**Comment by jniles** [comment]
This was closed in #92.
