### ISSUE TITLE
Report download `filename` attribute

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#102]
CSV rendering/ file downloads were introduced in https://github.com/Vanga-Hospital/bhima-2.X/pull/89. Currently downloads are processed in a similar way to the `bh-print` component, which forces the file download or opened to have the name of the UUID stored on the server. 

I suggest that we implement a `filename` option on the server so that reports can optionally set the name of the file that should be sent if a download is requested. 

The component can also use the HTML5 `download` attribute ensuring that all file types are downloaded and treated in the same way. This will mean no files will be automatically opened but will be handled by the browsers download manager and presented to the user in the same way.

**Comment by jniles** [comment]
Potentially related to https://github.com/IMA-WorldHealth/bhima-2.X/issues/1061.

**Comment by jniles** [comment]
@sfount, did this get fixed?

**Comment by jniles** [comment]
Closed in https://github.com/Vanga-Hospital/bhima-2.X/pull/108.
