### ISSUE TITLE
(design) Reverse Barcode Lookup

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#11]
In order to facilitate the barcode encoding scheme described in #9, the server will need a route to lookup barcodes and return the correct entity.

This will require the development of a `controllers/barcode.js` server controller.  The controller will be responsible for parsing incoming barcodes, retrieving the correct uuid, and then returning the entity JSON as if it were queried with the correct route.

In pseudo-code, this would be as follows:
```js

// load modules
const Patients = require('./medical/patients');
const Invoices = require('./finance/invoices');
// ... etc ...

// hard-coded barcode route definitions from issue #5
const identifiers = {
  'PA' : { controller : Patients, table : 'patient' },
  'IV' : { controller: Invoices, table : 'invoice' }
};

exports.barcode = (req, res, next) => {
  const code = req.body.barcode;  // 'PAc44619e03a8';

  // get the identifier
  const id = code.substr(0, 2);

  // destructure
  let controller, table;
  try {
    let { controller: controller, table: table } = identifiers[id];
  } catch (e) {
    return next(new BadRequest('unreadable barcode'));
  }

  const sql = `SELECT BUID(uuid) FROM ${table} WHERE LEFT(uuid, LENGTH(?)) = PartialUuid(?);`

  db.exec(sql)
    .then(rows => {
       if (rows.length > 1) {
         throw new BadRequest('unreadble barcode');
       }
     
      return controller.read(uuid);
    })
    .catch(next)
    .done();
};
```

For this implementation, we'll need to implement the MySQL function `PartialUuid()` to convert a 12 character UUID into a Binary UUID.

**Comment by sfount** [comment]
The `identifiers` definition here should be available for all services/ controllers that have to show human readable ids in https://github.com/Vanga-Hospital/bhima-2.X/issues/7

**Comment by jniles** [comment]
Yeah, the design for identifiers is still evolving.  I'll update the issue as needed.

**Comment by sfount** [comment]
This design was implemented and closed with https://github.com/Vanga-Hospital/bhima-2.X/pull/117. 

Currently the implementation uses `LIKE` on selected BUID(uuid). This allows for selection given any length of UUID however it may have performance implications in the future. The method described here should be more optimal with a clean implementation of `PartialUuid`
