### ISSUE TITLE
Include currency search in cash payments filter

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#12]
The cash payments module should be able to filter on the currency of the payment.

**Comment by jniles** [comment]
It should also show totals in both currencies at the bottom of the printed report.  If there is only one currency, it can only show a single total.

**Comment by sfount** [comment]
I agree! https://github.com/Vanga-Hospital/bhima-2.X/issues/13

**Comment by jniles** [comment]
I'll tackle this one along with #13.
