### ISSUE TITLE
Order by 'date registered'/ created_at on all registries

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#123]
Currently the Patient Registry does not have a default order. This can be quite confusing as the patients displayed are a mix of new and old. 

I suggest that all registries showing system documents are registered by date created at by default. This should show the newest and probably most relent records first. 

If a user has just registered a patient, it may well be that patient that they are going to find, currently there are no guarantees about the patient that shows up at the top.

**Comment by jniles** [comment]
I'll take this one.
