### ISSUE TITLE
Update Dependency: ui-router 

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#125]
Our version of UI-Router is currently very out of date. I suggest that we update to 1.0 along with the other major dependency updates we have scheduled coming up. 

UI-Router has recently released the first release candidate for version 1. This would give us performance improvements as well as new features for more cleanly watching for $state transitions etc. It would also make sure that our dependency does not become unsupported.

**Comment by jniles** [comment]
See also: https://github.com/IMA-WorldHealth/bhima-2.X/issues/1086
