### ISSUE TITLE
(refactor) Remove bhFindPatient from registry searches.

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#128]
This bhFindPatient directive wasn't really designed to fit into modals on small screens.  The typeahead box overflows:hidden on the modal, and overall it is not a pleasant user experience.

If you are searching for a patient, you probably know their name or ID.  I propose that we remove all `bhFindPatient` components on search modals to replace with either (or both) `ID` and `Patient Name` inputs that use a `LIKE %input%` SQL statement.

**Comment by sfount** [comment]
Agreed. The difference in having to 'submit' on this component before searching was very difficult for all users to understand .

**Comment by jniles** [comment]
Closed in https://github.com/Vanga-Hospital/bhima-2.X/pull/229
