### ISSUE TITLE
(Feature) Show totals in cash payments registry report

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#13]
The cash payments registry report would be an excellent place to start ensuring that hospitals can collect reliable data with the system (ensuring cash counts are correct). 

I suggest we add the following features to the cash payments registry report to facilitate that: 
* Signature line on the report (potentially optionally but for now as standard) 
* Display totals for all currencies, only show currencies that are included in the cash payments for the current filters

We could also consider adding a `ui-grid` custom aggregation that shows totals for all currencies in the cash payments module.

**Comment by jniles** [comment]
I'll take this.
