### ISSUE TITLE
bug(journal): Posting journal transactions with multiple `record_uuid`(s)

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#133]
Currently there are no correct use cases where a posting journal transaction should ever reference multiple `record_uuid`s; all transactions should be posted from one entity (invoice, cash_payment, voucher, etc.). 

There are a number of badly formed records in the posting journal where the `trans_id` encompasses either two transactions or even partial transactions. 

To begin investigating this; the following SQL brings up all records in the posting journal (unique `trans_id`) that contain multiple `record_uuid`s.

```sql
select trans_id, record_uuid, unique_records from (select trans_id, BUID(record_uuid) as record_uuid, COUNT(DISTINCT(record_uuid)) as unique_records from posting_journal group by trans_id order by trans_id) as c where c.unique_records > 1;
```

Currently: 
| trans_id |
| ---------- |
| HEV15 |
| HEV240 |
| HEV503 |
| HEV685 |

This issue was originally observed on HEV503.

As this seems to be incorrectly assigned transaction IDs to correct records (invoices, cash_payments) the problem may be something to do with the `GenerateTransactionId` function.

**Comment by sfount** [comment]
Note that currently we define the `transaction_id_length` in this method as 4. 

The current install enterprise has an abbreviation with length 3 - this could be causing very inconsistent assignment of transaction IDs and may well be relevant to this bug.

**Comment by jniles** [comment]
... oh yeah.  I forgot about that configuration parameter.  I assume the same thing is the case at the LUK install...

We need to figure out a better way to expose these parameters and set them prior to install.

**Comment by sfount** [comment]
I don't think it would work to set them prior to install as a project abbreviation can be any number of characters and you can have any number of different projects. 

As it currently stands project abbreviations can also be updated/ changed. 

Currently we pass in the `project_id` to request the transaction_id. 

It seems like we could calculate the abbreviation length before doing calculations on the posting journal, this would also remove the need for the large join on project on both journal and general ledger.

I can't guarantee that it will resolve this bug however.

**Comment by jniles** [comment]
This bug hasn't shown up in production since the merge of https://github.com/Vanga-Hospital/bhima-2.X/pull/173.
