### ISSUE TITLE
(refactor): standardize all our date inputs to use DD-MM-YYYY syntax

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#135]
Our application uses various date input standards: 'DD/MM/YYYY', 'YYYY-MM-DD', 'DD-MM-YYYY'.  I recommend we pick one and stick to it.  My preference is 'DD-MM-YYYY'.

**Comment by sfount** [comment]
As @lomamech points out in https://github.com/IMA-WorldHealth/bhima-2.X/issues/1106, the standard date format in DRC is DD/MM/YYYY. Potentially this should be the format used going forward? 

@mbayopanda could you look at standardising all date inputs on the client? It's important that this is done in a careful way with all users being updated about the change. 

Potentially the format could be defined in `bhConstants` to make sure all components are being driven by the same value.

**Comment by jniles** [comment]
@sfount , sounds good to me. I'm a fan then of changing all our journal separators to using ` - ` as well.  That otherwise, you might get:
```
IV.HEV.12/A typical invoice made for me/chirurgie/23/10/2015
```
Which is a bit harder to distinguish which is the date component.  If we use dashes a separators, we will avoid readability problems.

**Comment by jniles** [comment]
Closing in favor of https://github.com/IMA-WorldHealth/bhima-2.X/issues/1106.
