### ISSUE TITLE
(feature request) Print the Service next to the Invoice Identifier on the Cash Payment Receipt

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#142]
Our clients currently rely on the service of the bill to decide what services get rendered to a client.  It would be helpful to attache the service name next to (or underneath) the invoice identifier on the Cash Payment receipt so that the staff do not have to transcribe it each time.

**Comment by sfount** [comment]
@DedrickEnc worked on cash receipts in https://github.com/Vanga-Hospital/bhima-2.X/pull/194. This would be a good issue for him to review.
