### ISSUE TITLE
(feature request) Put the total balance of the Patient's account at the bottom of the Cash Receipt

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#144]
After each payment made, it would be useful for the patient to see their total balance with the hospital, if that balance is non-zero.  I recommend we set an option flag that will including the patient's balance when printing out the thermal receipts.  This will allow an institution to turn the feature off when it makes sense, or use it when that is better.

**Comment by sfount** [comment]
@DedrickEnc is working on adding this.

**Comment by jniles** [comment]
Note: this should be on both the POS and the larger receipts.

**Comment by jniles** [comment]
Closed in #194.
