### ISSUE TITLE
(chore) Merge Vanga-Hospital and IMA-WorldHealth branches

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#153]
The time has come to re-integrate the changes from Vanga into the master branch.  As soon as this merge is done, this issue should be closed.

**Comment by sfount** [comment]
I'll investigate this this morning, the `diff` should be looked at by the whole team; potentially a meeting should be held explaining new features and receiving feedback/ potentially required improvements.

**Comment by jniles** [comment]
Sounds good!

What will happen with fixes to Vanga that happen during the review process?  Should we created an `ima-merge` branch on the Vanga-Hospital repo to make sure that the PR is not constantly updated?

**Comment by sfount** [comment]
That's a good idea. I'm hoping the review process shouldn't take more than a day - following that all relevent changes will be kept up to date on the IMA master branch so that neither `master` gets out of date.

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1104.
