### ISSUE TITLE
(bug) No way to find the Credit Note for an Invoice from the Invoice Registry

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#159]
The invoice registry colors reversed (via credit note) records red.  Unfortunately, there is no way to find the associated credit note!  Even the voucher registry does not have a way to find the correct credit note.

The following changes need to be made:
 1. _At minimum_, the Voucher description must include the invoice reference.
 2. Allow the invoice registry to directly link the credit note (using [dropdowns #52](https://github.com/Vanga-Hospital/bhima-2.X/issues/52)).

**Comment by sfount** [comment]
There's no 'worried' reaction. 

This sounds like a very important change to me. Having a more robust way to link credit notes and invoices is a worth while use of time; I remember there was discussions about this in issues on the IMA-WorldHealth repository.

**Comment by sfount** [comment]
@mbayopanda is looking at what this takes.

**Comment by sfount** [comment]
The proposal for closing the issues is: 
* Dropdown select the optionally shows and hides the action to create a credit note or show its receipt based on if it has already been reversed. 
* @mbayopanda researched credit note receipts and thinks that credit notes for invoices should be more specific than a voucher receipt, showing information about the invoice 
* Including the invoice identifier in the description of the credit note
