### ISSUE TITLE
(feature request): Implement "Download as CSV" on every single registry

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#160]
Bhima now supports downloading as CSV ... this was implemented in https://github.com/Vanga-Hospital/bhima-2.X/pull/89 and improved in https://github.com/Vanga-Hospital/bhima-2.X/pull/108.  It would be good to have this functionality on every single registry page.

**Comment by sfount** [comment]
Agreed - I think this should land with a proposal I had for using a more uniform 'Actions menu' dropdown on modules. This is inspired by the download button being very long and not working at some of the smaller screen sizes that we are supported with older hardware. 

This functionality is not required and can be added before or after that, it should just be factored in. I'll look at making an issue for the work on registries that I've collected over the install.

**Comment by jniles** [comment]
Sounds good to me - this isn't necessarily pressing ... best to do it right the first time.

**Comment by sfount** [comment]
@lomamech has begun implementing this feature in each registries.

**Comment by jniles** [comment]
Looks like this was closed in #196.
