### ISSUE TITLE
(refactor) Data Formatters for CSV Renderer

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#161]
The [CSV renderer](https://github.com/Vanga-Hospital/bhima-2.X/blob/master/server/lib/renderers/csv.js) is very naive.  It uses the [json-2-csv](https://github.com/mrodrig/json-2-csv) defaults to export data.

I propose that we intercept the data to the CSV renderer and make sure it is in a human readable format when exported.  Currently, the module just uses the `toString()` method on everything.  For dates, this happens to look like this:
```sh
Wed Jan 18 2017 11:14:42 GMT+0100 (WAT)
```
Excel doesn't read this format.  Instead, it might be better to intercept the data and parse it to something more friendly.  For example:
```js
const _ = require('lodash');
const moment = require('moment');

// loop through an array of objects, converting dates to DD/MM/YYY
const convertIfDate = (v) => _.isDate(v) ? moment(v).format('DD/MM/YYYY') : v;
const dateFormatterFn = (row) => _.mapValues(row, convertIfDate);

// make all dates DD/MM/YYYY
rows.forEach(row => dateFormatter);
```

This would make the exports easier to deal with.

**Comment by sfount** [comment]
This could even be a flag that is enabled by default. Allowing the report to not have to think about formatting dates/ UUIDs etc. but allowing it to override this feature if it wants full control over what is sent to the client.
