### ISSUE TITLE
(bug) Trial Balance breaks on large request

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#166]
The Trial Balance was designed to use a GET request to send Transaction IDs back to the server.  Unfortunately, this breaks when there are large numbers items to send back as GET parameters with a [414 Request-URI Too Large HTTP](http://www.checkupdown.com/status/E414.html) error.

[This is the same problem as exists in 1.X with services](https://github.com/IMA-WorldHealth/bhima-1.X/issues/877).

When large amounts of data are being sent back to the server, they should always use POST requests.

![brokengetrequest](https://cloud.githubusercontent.com/assets/896472/22064794/6bd4c266-dd85-11e6-9003-634ab93e84de.png)
_Fig 1: The Broken GET Request_

**Comment by sfount** [comment]
This is an error that users cannot resolve themselves in any way and I think it should be tackled as soon as possible. @DedrickEnc if you could take a look at this.
