### ISSUE TITLE
(feature request) Add .csv extension to the csv filenames

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#178]
We provide a very nice way to download files with appropriate filenames.  It would be nice to include an extension with the CSV renderer specifically, and all renderers in general to allow the user's computer to interpret the MIME type more easily.

**Comment by sfount** [comment]
On my machine the file type is interpreted correctly and the files have the correct extension when downloaded. 

Machines interpretation of downloaded files: 
![screenshot 2017-01-25 at 10 46 24](https://cloud.githubusercontent.com/assets/2844572/22285379/ba3d0074-e2eb-11e6-8b29-7ca4496c61ea.png)

Is this behaviour different for you?

**Comment by jniles** [comment]
Hmmm...  That is correct.  I guess technically the cash payments and invoices CSV rendered reports aren't implemented yet.  I was doing some direct API calls to render them, so this isn't actually a feature or a bug yet :)

... but in the future, when they are actually implemented, they should use the CSV extension!

**Comment by sfount** [comment]
Agreed! 

This feature is currently being implemented on all registries by @lomamech https://github.com/Vanga-Hospital/bhima-2.X/issues/160 so that should close this issue.

**Comment by jniles** [comment]
I can confirm that this is fixed.  Great work!
