### ISSUE TITLE
(refactor): remove bhFindPatient component from all search forms

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#203]
The `bhFindPatient` component is useful for locating patients for data entry into a larger form.  It does not make sense on the search forms of registries.  I propose we remove the `bhFindPatient` component from those places and replace it with a simple `Patient Reference` search input.

**Design** 
The reference input should take in a text field like `PA.TPA.123` and map to a filter on the server that looks for a patient with that reference.

**Comment by jniles** [comment]
@DedrickEnc , could you look into this one?

**Comment by DedrickEnc** [comment]
ok

**Comment by DedrickEnc** [comment]
This reference input will be an angular component?

**Comment by jniles** [comment]
It doesn't have to be.  Just a regular:
```
<input ng-model="$ctrl.model.value" >
```
will work fine.

**Comment by DedrickEnc** [comment]
Sorry, I am not seeing a ```bhFindPatient``` in any registry may be I am not understanding.

**Comment by jniles** [comment]
https://github.com/Vanga-Hospital/bhima-2.X/blob/master/client/src/partials/patient_invoice/registry/search.modal.html#L104
