### ISSUE TITLE
(Proposal) Only test on supported versions of NodeJS

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#214]
We have lots of failing Travis tests these days.  A likely cause is that we are testing on NodeJS version 4 ... which is out of date now.  [The current NodeJS LTS support is v6.9](https://nodejs.org/en/).  Even [Protractor](https://github.com/angular/protractor/commit/0555d394ce87eb7d12cbf3a33881dac54fb740fd) now recommends that its minimum version number be 6.9.x and will make this change required in their next release.

I propose we revise our Travis testing to test on the current LTS version of Node (v6 in this case) and the next version (v7 in this case) with the plan being to upgrade all installations as we need them.

**Comment by sfount** [comment]
Agreed, given our current control of the installation environment. This should speed up automated testing significantly.

If there is a specific requirement for older environments in the future we can investigate what has to be done to support them.
