### ISSUE TITLE
(feature request) Print out Patient Thermal Receipt for identification

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#22]
The Patient Card is a robust identification card ... however, it may not be practical for some cases.  One client recommendation is to print a small barcoded identification piece for the patient that they can use for a single patient visit.  This identity piece will include:
 1. Name
 2. Age
 3. Sex
 4. The short barcode proposed in #9.

This should follow the same design principles of the Patient Invoicing thermal receipt.

**Comment by sfount** [comment]
I am looking at implementing the short bar-code propose in #9. As the same
libraries could be used I suggest that the receipt is made first and then
the barcode is implemented once the bar codes are added to patient invoice
POS receipts.

*Steven Fountain*
Democratic Republic of Congo
*Phone: *+243 825763664 <+243%825763664>
*Skype: *stevenfountain

Facebook <https://www.facebook.com/imaworldhealth> | Twitter
<https://twitter.com/imaworldhealth> | LinkedIn
<https://www.linkedin.com/company/441163?trk=tyah&trkInfo=tarId%3A1423079895689%2Ctas%3AIMA%20World%20Health%2Cidx%3A1-1-1>

Donate Today! <https://imaworldhealth.org/donate/>
