### ISSUE TITLE
(refactor) Move `transaction_type` values into `bhima.sql` 

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#230]
Currently our default transaction types are defined in `test/data.sql`, however the application depends on certain vouchers having certain type_ids - this can usually be found in checking for reversals/ specific operations. 

The transaction type definition should be moved to guarantee these IDs throughout the application.

**Comment by jniles** [comment]
These have been moved into `bhima.sql` on master.  It was closed in https://github.com/Vanga-Hospital/bhima-2.X/commit/9379f04307cd7a78b346249354ec42ec2648a32a.
