### ISSUE TITLE
(feature request) Link between registry of patients to invoices/ cash payments 

### ISSUE THREAD

**Issue by sfount** [Vanga-Hospital/bhima-2.X#253]
Following on from the work done in https://github.com/Vanga-Hospital/bhima-2.X/pull/251 (regarding https://github.com/Vanga-Hospital/bhima-2.X/issues/199). I propose that we add links from the patient registry into lists of invoices and cash payments. 

This would allow the patient registry to always be the first place a user goes to look up information on a patient. Once the patient has been found the user can easily navigate to lists of all of that patients invoices or cash payments. 

This could be implemented as two additional 'actions' on the patient registry page. Make the actions dropdown look like

| Action | Description |
| --- | --- | 
| View Record | Link to the patients record page | 
| Edit Patient | Edit the patients details |
| View Patient Identity | Open the patients identity card in a modal | 
| --- | --- |
| View Invoices | Link to the invoice registry filtered on this patient | 
| View Cash Payments | Link the cash payment registry filtered on this patient |

**Comment by jniles** [comment]
Closed in https://github.com/IMA-WorldHealth/bhima-2.X/pull/1140
