### ISSUE TITLE
(feature request) "Deactivate" a user

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#260]
Sometimes, a system administrator may need to delete a user.  Instead of deleting the user entirely, I propose that we simply add a `deactivated` flag to the user table, and ensure that users that are deactivated are grayed out in the list of users with a `DEACTIVATED` label.  These users will no longer be able to log in.  This has the advantage of essentially deleting a user without remove them entirely.

**Comment by DedrickEnc** [comment]
I will take it!

**Comment by jniles** [comment]
Sounds good to me!

**Comment by DedrickEnc** [comment]
I have seen a column called active in the table user, can I use it?

**Comment by jniles** [comment]
Hmm... that was originally for figuring out if a user was logged in, but I guess we don't need it.  I'm okay with you using it.  @sfount, what do you think?

**Comment by sfount** [comment]
Given this discussion it would seem `active` is ambiguous. 

The advantages of `deactivated` are: 
* Not ambiguous - `deactivated=1` clearly means that account is not longer in use 
* The default behaviour is for a user to be activated, having the default value as false (i.e the flag is negative) makes more sense to me in this case 

Unless adding a new field proves to be difficult, I would recommend the original proposal.

**Comment by DedrickEnc** [comment]
ok
