### ISSUE TITLE
(bug) wkhtmltopdf does not detect the stylesheets anymore.

### ISSUE THREAD

**Issue by jniles** [Vanga-Hospital/bhima-2.X#74]
For some reasons, an update (likely to `ReportManager` or the `pdf` renderer) broke the css for the receipts/reports.  An example is show below:

![nocssreportpdf](https://cloud.githubusercontent.com/assets/896472/21693057/be556d16-d37f-11e6-98a0-cd71538f3539.png)
_Fig 1: Receipt with broken CSS_

This should be fixed as soon as possible.

**Comment by sfount** [comment]
This is caused by the head template file no longer requiring bootstrap CSS. I'll submit a fix shortly.
